// <auto-generated />
using InterfaceAdapters_Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace InterfaceAdapters_Data.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20250425120259_Update")]
    partial class Update
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.4")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("InterfaceAdapters___Models.AlumnoModel", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Apellido")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("NroTelefono")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("Observaciones")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Alumno", (string)null);
                });

            modelBuilder.Entity("InterfaceAdapters___Models.HorarioModel", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Dia")
                        .IsRequired()
                        .HasMaxLength(15)
                        .HasColumnType("nvarchar(15)");

                    b.Property<string>("Hora")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)");

                    b.HasKey("Id");

                    b.ToTable("Horario", (string)null);
                });

            modelBuilder.Entity("InterfaceAdapters___Models.InstructorModel", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Apellido")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("NroTelefono")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<int>("PorcentajeDePago")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("Instructor", (string)null);
                });

            modelBuilder.Entity("InterfaceAdapters___Models.TurnoAlumnoModel", b =>
                {
                    b.Property<int>("AlumnoId")
                        .HasColumnType("int");

                    b.Property<int>("TurnoId")
                        .HasColumnType("int");

                    b.HasKey("AlumnoId", "TurnoId");

                    b.HasIndex("TurnoId");

                    b.ToTable("TurnoAlumno", (string)null);
                });

            modelBuilder.Entity("InterfaceAdapters___Models.TurnoModel", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("Capacidad")
                        .HasColumnType("int");

                    b.Property<int>("HorarioId")
                        .HasColumnType("int")
                        .HasColumnName("HorarioId");

                    b.Property<int?>("InstructorId")
                        .HasColumnType("int")
                        .HasColumnName("InstructorId");

                    b.HasKey("Id");

                    b.HasIndex("HorarioId");

                    b.HasIndex("InstructorId");

                    b.ToTable("Turno", (string)null);
                });

            modelBuilder.Entity("InterfaceAdapters___Models.TurnoAlumnoModel", b =>
                {
                    b.HasOne("InterfaceAdapters___Models.AlumnoModel", "Alumno")
                        .WithMany("TurnoAlumnos")
                        .HasForeignKey("AlumnoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("InterfaceAdapters___Models.TurnoModel", "Turno")
                        .WithMany("TurnoAlumnos")
                        .HasForeignKey("TurnoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Alumno");

                    b.Navigation("Turno");
                });

            modelBuilder.Entity("InterfaceAdapters___Models.TurnoModel", b =>
                {
                    b.HasOne("InterfaceAdapters___Models.HorarioModel", "Horario")
                        .WithMany("Turnos")
                        .HasForeignKey("HorarioId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("InterfaceAdapters___Models.InstructorModel", "Instructor")
                        .WithMany("Turnos")
                        .HasForeignKey("InstructorId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("Horario");

                    b.Navigation("Instructor");
                });

            modelBuilder.Entity("InterfaceAdapters___Models.AlumnoModel", b =>
                {
                    b.Navigation("TurnoAlumnos");
                });

            modelBuilder.Entity("InterfaceAdapters___Models.HorarioModel", b =>
                {
                    b.Navigation("Turnos");
                });

            modelBuilder.Entity("InterfaceAdapters___Models.InstructorModel", b =>
                {
                    b.Navigation("Turnos");
                });

            modelBuilder.Entity("InterfaceAdapters___Models.TurnoModel", b =>
                {
                    b.Navigation("TurnoAlumnos");
                });
#pragma warning restore 612, 618
        }
    }
}
